import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import topics from "./api/topics.json";

export default function Home() {


  const topicsRender = topics?.data?.map((topic, index) => {
    return <div className={styles.card} key={index}>
      <Link href={`/learn/${topic}`}>Learn {topic} Page</Link>
    </div>
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Link href={"/hello"}>Hello Page</Link>
          </div>
          <div className={styles.card}>
            <Link href={"/about"}>About Page</Link>
          </div>
          <div className={styles.card}>
            <Link href={"/learn/next"}>Learn NextJS Page</Link>
          </div>
        </div>
        <div className={styles.grid}>
          {topicsRender}
        </div>

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
